### ISSUE TITLE
Ваня, это пицца!

### ISSUE THREAD

**Issue by stereoyana** [johnnovikov/MSHP-CTF#10]
```
def main():
    a=int(input('введи 1 число '))
    b=int(input('введи 2 число '))
    rez=a+b
    print(a,'+',b,rez,sep'')
main()
```
помогите пожалуйста найти ошибку

**Comment by jnovikov** [comment]
Ошибки нет.

**Comment by jnovikov** [comment]
Нет, это не пицца

**Comment by segaRock** [comment]
#!/usr/bin/env python3.6
# -*- codding: UTF-8 -*-

def pizza():
    a = int(input('Введите 1 число: '))
    b = int(input('Введите 1 число: '))
    rez = a + b
    greetings = print(a, "+", b, "is equal: ", rez)

    return greetings

if __name__ == '__main__':
    pizza()

**Comment by segaRock** [comment]
def pizza():
    a = int(input('Введите 1 число: '))
    b = int(input('Введите 1 число: '))
    rez = a + b
    greetings = print(a, "+", b, "is equal: ", rez)

    return greetings

if __name__ == '__main__':
    pizza()

**Comment by segaRock** [comment]
![default](https://user-images.githubusercontent.com/7660291/31272870-22bff1d0-aa95-11e7-8143-b52a5e702877.PNG)

Наверное типа того что-то хотелось?

**Comment by stereoyana** [comment]
как ты вообще сюда попал, лол?

**Comment by segaRock** [comment]
Случайно xD

**Comment by stereoyana** [comment]
тестируем

**Comment by segaRock** [comment]
What's new?
